/* Session 8 — the chronological record of attention.
   Every `date` and `src` below was checked against the arXiv abstract page or the
   primary release before it was written here. Nothing is from memory. The README
   in ../session-08-attention-timeline/ carries the same table with links.

   lane: core | compute | memory | position
     core     — the mechanism itself, or a change to what it computes
     compute  — pays down the T-squared score work
     memory   — pays down the KV cache / recurrent state
     position — makes position survive a length it was not trained at          */

const MECHANISMS = [
{
  id: "bahdanau", date: "2014-09-01", year: 2014, lane: "core",
  name: "Attention (additive)", who: "Bahdanau, Cho & Bengio",
  src: "arXiv:1409.0473", url: "https://arxiv.org/abs/1409.0473",
  tag: "the original",
  problem: "A seq2seq encoder crushes an entire source sentence into one fixed-width vector. Translation quality falls off a cliff as sentences get longer, because everything has to fit through that bottleneck.",
  mech: "Let the decoder look back at <em>all</em> encoder states and take a weighted sum of them, where the weights come from a small learned alignment network scoring each (decoder state, encoder state) pair.",
  buys: ["No fixed-width bottleneck — capacity grows with the source.", "Long-sentence translation stops degrading.", "The weights are inspectable: you can see what aligned to what."],
  costs: ["Still recurrent, so still strictly sequential — no parallelism over sequence length.", "The alignment MLP runs once per pair, which is already a quadratic cost nobody was worried about yet."],
  pick: "Historical. Nothing ships this. But every score → weight → sum mechanism below is this one, and it is <b>three years older than the transformer</b> — a fact the usual telling skips.",
},
{
  id: "sdpa", date: "2017-06-12", year: 2017, lane: "core",
  name: "Scaled dot-product attention + multi-head", who: "Vaswani, Shazeer, Parmar, Uszkoreit, Jones, Gomez, Kaiser & Polosukhin",
  src: "arXiv:1706.03762", url: "https://arxiv.org/abs/1706.03762",
  tag: "the baseline",
  problem: "Recurrence is the parallelism bottleneck. If attention can already reach every position, what is the RNN still for?",
  mech: "Remove the RNN entirely. Every token projects to a query, a key and a value; score with <code>QKᵀ/√d_k</code>, mask the future, softmax, and take the weighted sum of values. Split the width into h heads so several relations can be tracked at once.",
  buys: ["Any token reaches any other in <b>one</b> step, not O(distance) steps.", "Fully parallel over sequence length during training — this is what made scaling possible.", "The learned alignment MLP collapses into a dot product, which is free on a GPU.", "Heads specialise on their own; nothing assigns them."],
  costs: ["<b>T² scores, per head, per layer</b> — the bill the next eight years are spent paying down.", "The score matrix must be written to memory and read back, which turns out to matter more than the arithmetic (see 2022).", "Completely order-blind. Position has to be injected from outside, which is the second thread of this timeline."],
  pick: "Below about 4K tokens, still the correct default. The bills only bite when T gets large; under that, exactness is cheap and everything here is a solution to a problem you do not have.",
},
{
  id: "sinusoidal", date: "2017-06-12", year: 2017, lane: "position",
  name: "Sinusoidal positions", who: "Vaswani et al., §3.5",
  src: "arXiv:1706.03762", url: "https://arxiv.org/abs/1706.03762",
  tag: "computed, not stored",
  problem: "Attention reads a set. Shuffle the input and the output shuffles with it — the mechanism has no idea which token came first.",
  mech: "Add a fixed vector of sines and cosines at geometrically-spaced frequencies to each token embedding. No parameters; the value at any position is computed, not looked up.",
  buys: ["Zero parameters.", "Defined at <em>every</em> position, including ones never seen in training.", "Linear-combination structure means relative offsets are in principle recoverable."],
  costs: ["Added to the embedding, so position and content share the same channels and dilute each other.", "The paper reports it performs about the same as a learned table — so nobody was forced to prefer it, and most of the field went with learned anyway."],
  pick: "Rarely, now. Its importance is that it was the first <b>computed</b> position signal, and computed-beats-stored is the thread that ends at RoPE and then at DroPE.",
},
{
  id: "learned-abs", date: "2017-05-08", year: 2017, lane: "position",
  name: "Learned absolute positions", who: "Gehring, Auli, Grangier, Yarats & Dauphin (ConvS2S)",
  src: "arXiv:1705.03122", url: "https://arxiv.org/abs/1705.03122",
  tag: "the wall",
  problem: "Same problem, and it arrived first — ConvS2S dropped recurrence a month before the transformer did, and hit the ordering question immediately.",
  mech: "A trainable table with one vector per position, added to the token embedding. Gathered on the forward pass and scatter-added on the backward, exactly like a token embedding table.",
  buys: ["As simple as it gets.", "Assumes nothing about the structure of position — the model learns whatever the data actually has."],
  costs: ["<b>A hard wall.</b> Row 4,097 was never trained. Worse, nothing in the parameters connects row 4,095 to row 4,096 — the table does not know positions are ordered.", "Your context length is frozen when training starts. Claiming 1M context means training on 1M-token sequences."],
  pick: "Effectively obsolete. It is on this timeline because it is the thing everything in the position lane is running away from — and because the same failure reappeared in 2026 inside Kronecker embeddings, where a stored byte-position one-hot capped tokens at 32 bytes.",
},
{
  id: "txl", date: "2019-01-09", year: 2019, lane: "memory",
  name: "Transformer-XL (segment recurrence)", who: "Dai, Yang, Yang, Carbonell, Le & Salakhutdinov",
  src: "arXiv:1901.02860", url: "https://arxiv.org/abs/1901.02860",
  tag: "state across the boundary",
  problem: "Long documents get chopped into fixed segments, and everything is thrown away at each cut. A sentence spanning a boundary is simply lost — 'context fragmentation'.",
  mech: "Cache the previous segment's hidden states and let the current segment attend to them, with the gradient <b>stopped</b> at the boundary. Absolute positions break when segments slide, so it also introduces relative positional encoding.",
  buys: ["Dependencies ~450% longer than a vanilla transformer.", "No training graph spans the whole document, so memory stays bounded.", "Relative position, three years before RoPE."],
  costs: ["The carried state is O(segment length) per layer, not O(1).", "Because the gradient is cut, the model never learns <em>how to write</em> a good summary — only how to read whatever it is handed."],
  pick: "Rarely as-is. It is here because it is the direct ancestor of every cross-chunk memory since — including LightningLM V4's Memory Stream, whose two defining choices (carry a summary forward, stop the gradient) are both from this paper.",
},
{
  id: "sparse-tx", date: "2019-04-23", year: 2019, lane: "compute",
  name: "Sparse Transformer", who: "Child, Gray, Radford & Sutskever (OpenAI)",
  src: "arXiv:1904.10509", url: "https://arxiv.org/abs/1904.10509",
  tag: "first attack on T²",
  problem: "Nothing. That is the point — for <b>two years</b> nobody optimised attention, because at the lengths people used, T² was not yet the thing that hurt. This is the paper where it starts hurting.",
  mech: "Factorize the attention pattern. Each token attends along a strided or fixed subset of positions, chosen so that two hops still connect any pair. O(n√n) instead of O(n²).",
  buys: ["Sequences of tens of thousands of steps become feasible.", "The first credible demonstration that attention does not have to be dense."],
  costs: ["<b>The pattern is fixed, not content-dependent.</b> It cannot notice that the one token you needed was in the block it skipped.", "Needs custom kernels, which in 2019 meant almost nobody could run it."],
  pick: "Superseded — but read the date against 2025. It took <b>six years</b> to get from this to sparsity that is trained rather than bolted on.",
},
{
  id: "mqa", date: "2019-11-06", year: 2019, lane: "memory",
  name: "Multi-Query Attention (MQA)", who: "Shazeer",
  src: "arXiv:1911.02150", url: "https://arxiv.org/abs/1911.02150",
  tag: "the second bill, found",
  problem: "A different bill entirely, and it shows up seven months after the first. Incremental decoding is <b>memory-bandwidth bound</b>, not FLOP bound — you reload the entire KV cache to generate each single token.",
  mech: "Keep all the query heads. Share <b>one</b> key head and <b>one</b> value head across all of them.",
  buys: ["Cache shrinks by the head count — 8× for 8 heads.", "Decoding gets dramatically faster, because the thing you were waiting on was the memory read."],
  costs: ["Quality loss, and training instability.", "Every query head now searches the same index, which is exactly the diversity that multi-head existed to provide."],
  pick: "Almost never, directly — it was too lossy and the field mostly waited. That wait is the point: <b>the compromise (GQA) took four more years</b>, and it is the compromise everybody ships.",
},
{
  id: "longformer", date: "2020-04-10", year: 2020, lane: "compute",
  name: "Sliding window attention", who: "Beltagy, Peters & Cohan (Longformer)",
  src: "arXiv:2004.05150", url: "https://arxiv.org/abs/2004.05150",
  tag: "locality is usually enough",
  problem: "Same T² bill, and the fixed strided pattern of 2019 is awkward for text, where what matters is usually nearby.",
  mech: "Each token attends to a window of w neighbours, plus a handful of designated global tokens that attend everywhere and are attended by everyone. Stack L layers and the receptive field is L×w.",
  buys: ["Linear in T.", "A genuine drop-in replacement for standard attention.", "Simple enough that it actually got used — Mistral 7B shipped it."],
  costs: ["Information moves only w positions per layer, so a long-range dependency has to be paid for in <b>depth</b>.", "The global tokens are hand-picked. That is a task-specific decision wearing an architecture costume."],
  pick: "When local structure genuinely dominates and you have depth to spare. Still a good, boring, effective choice — and it is a component inside NSA six years later.",
},
{
  id: "linear", date: "2020-06-29", year: 2020, lane: "compute",
  name: "Linear attention", who: "Katharopoulos, Vyas, Pappas & Fleuret",
  src: "arXiv:2006.16236", url: "https://arxiv.org/abs/2006.16236",
  tag: "delete the softmax",
  problem: "Every sparsity scheme is still choosing <em>which</em> T² entries to skip. Is the quadratic itself avoidable? It is — but softmax is in the way, because its shared denominator couples every score to every other and forbids reassociating the product.",
  mech: "Replace <code>exp(qᵀk)</code> with <code>φ(q)ᵀφ(k)</code> for a feature map φ. Then <code>(φ(Q)φ(K)ᵀ)V = φ(Q)(φ(K)ᵀV)</code> — and the right-hand grouping never builds a T×T matrix. Autoregressively this is an RNN whose matrix state does not grow with T.",
  buys: ["O(T) training and <b>O(1) per-token generation</b>.", "The state is the same size after a million tokens as after ten.", "Up to 4000× faster autoregressive inference in the paper's own measurements."],
  costs: ["<b>Everything softmax was doing.</b> Weights are no longer positive and no longer sum to one, so outputs drift with length.", "The whole past is compressed into one state, so distinct memories interfere.", "Recall of a specific old token degrades badly — which is the failure that defines this family for the next five years."],
  pick: "In 2020, essentially never alone. It took the delta rule <em>and</em> gating <em>and</em> a parallel kernel to make this competitive — three separate unlocks spread over four years.",
},
{
  id: "delta", date: "2021-02-22", year: 2021, lane: "memory",
  name: "The delta rule (DeltaNet)", who: "Schlag, Irie & Schmidhuber",
  src: "arXiv:2102.11174", url: "https://arxiv.org/abs/2102.11174",
  tag: "a state that can be corrected",
  problem: "A linear-attention state is <b>add-only</b>. If key A currently returns 40 and should now return 55, writing 55 gives you 95. The state can accumulate; it cannot revise. That is an accumulator, not a memory.",
  mech: "Before writing, read what the state currently returns for this key, and write only the <em>difference</em>: <code>S ← S + β(v − Sk)kᵀ</code>. The classic delta rule, applied to a fast-weight matrix.",
  buys: ["The state becomes an editable memory.", "Associative recall improves sharply — the exact weakness of 2020 linear attention."],
  costs: ["<b>The update is sequential.</b> Each write depends on reading the state the previous write produced, so it does not parallelise over sequence length — and on a GPU that is fatal.", "Still one fixed state, so still lossy at long range."],
  pick: "In any fixed-state design. But look at the date: this idea then sat unusable for <b>three years</b>. Not because it was wrong — because no one could train it fast enough.",
},
{
  id: "rope", date: "2021-04-20", year: 2021, lane: "position",
  name: "RoPE (rotary position embedding)", who: "Su, Lu, Pan, Murtadha, Wen & Liu (RoFormer)",
  src: "arXiv:2104.09864", url: "https://arxiv.org/abs/2104.09864",
  tag: "rotate, don't add",
  problem: "Absolute tables hit a wall; sinusoidal-added-to-embedding mixes position into content. And what attention actually needs is not 'I am token 8' but 'that token is six behind me'.",
  mech: "Take Q and K in 2-D pairs and rotate each pair by p·θ. A dot product depends only on the angle <em>between</em> two vectors, so the absolute rotations cancel: <code>R(iθ)q · R(jθ)k = q · R((j−i)θ)k</code>. The positional term depends on <b>i−j alone</b>.",
  buys: ["Relative position appears inside the score for free.", "No parameters, and defined at any position — a circle has no last position.", "Applied to <b>Q and K only</b>, inside attention, so V is never contaminated.", "Different frequency bands give the head several distance scales at once."],
  costs: ["<b>Defined at any position is not trained at any position.</b> Past roughly 8K–16K the rotations reach configurations the model never saw, and long-range attention degrades.", "It bakes a specific distance geometry into the architecture."],
  pick: "Essentially always, 2021 through 2025. It is the default — and the entire 2023 extension literature exists to patch its one failure mode.",
},
{
  id: "alibi", date: "2021-08-27", year: 2021, lane: "position",
  name: "ALiBi (attention with linear biases)", who: "Press, Smith & Lewis",
  src: "arXiv:2108.12409", url: "https://arxiv.org/abs/2108.12409",
  tag: "the opposite bet",
  problem: "The same one RoPE addressed — four months later, and with a completely different philosophy. Worth reading side by side, because the field genuinely did not know which would win.",
  mech: "Don't encode position at all. Subtract <code>m·|i−j|</code> from every attention score, with a fixed per-head slope m. Closer tokens are simply penalised less.",
  buys: ["Trivially cheap — no embedding, no rotation, one subtraction.", "Extrapolates to sequences longer than it trained on, which was the headline: <em>train short, test long</em>.", "Each head gets a different slope, so the model has several recency scales."],
  costs: ["<b>It hard-codes a monotonic recency prior.</b> The model cannot learn that a token 4,000 back matters more than one 10 back — the bias forbids it.", "Fine for language-modelling perplexity. Bad for retrieval over long context, which is what long context is usually <em>for</em>."],
  pick: "When recency genuinely dominates and you want extrapolation for free. It lost to RoPE-plus-extension, and the reason is precise: the prior that buys the extrapolation is the same prior that ruins long-range retrieval.",
},
{
  id: "flash", date: "2022-05-27", year: 2022, lane: "compute",
  name: "FlashAttention", who: "Dao, Fu, Ermon, Rudra & Ré",
  src: "arXiv:2205.14135", url: "https://arxiv.org/abs/2205.14135",
  tag: "★ exact, and cheaper anyway",
  starred: true,
  problem: "Every entry above assumes making attention cheaper requires making it <em>approximate</em>. That assumption is wrong, and this paper is where it breaks. The real bottleneck was never the arithmetic — it was writing the T×T score matrix out to HBM and reading it back.",
  mech: "Tile the computation so blocks of Q, K and V stay in on-chip SRAM; fuse the softmax into the matmuls using the online-softmax trick so the full score matrix is <b>never materialised</b>; recompute it in the backward pass instead of storing it.",
  buys: ["<b>Exact.</b> Bit-for-bit the same result as standard attention — no approximation, no quality trade, nothing to ablate.", "2–4× faster wall-clock, and O(T) memory instead of O(T²).", "Enabled longer context on hardware people already owned, immediately."],
  costs: ["Still quadratic in <em>work</em>. It moves the wall a long way; it does not remove it.", "It is a kernel, so it must be rewritten for every new accelerator and every new mask shape."],
  pick: "<b>Always.</b> This is the entry the syllabus omits, and it is the one that most changes how the timeline reads: it redefined what 'expensive' meant, and the approximation literature went quiet for roughly two years afterwards.",
},
{
  id: "gqa", date: "2023-05-22", year: 2023, lane: "memory",
  name: "GQA (grouped-query attention)", who: "Ainslie, Lee-Thorp, de Jong, Zemlyanskiy, Lebrón & Sanghai",
  src: "arXiv:2305.13245", url: "https://arxiv.org/abs/2305.13245",
  tag: "the compromise that shipped",
  problem: "MQA saved the cache in 2019 and almost nobody adopted it, because one shared KV head cost too much quality. Four years of a known solution going unused.",
  mech: "Interpolate. Instead of H key/value heads (MHA) or 1 (MQA), use G groups — e.g. 8 query heads sharing 2 KV heads. And crucially: show how to <b>uptrain an existing MHA checkpoint</b> into GQA with about 5% of the original pretraining compute.",
  buys: ["Most of MQA's cache saving at close to MHA quality.", "Retrofittable — you do not have to retrain from scratch, which is why adoption was near-universal within a year."],
  costs: ["<b>It lowers the slope; it does not stop the line.</b> The cache still grows linearly in T.", "At 1M context, GQA is still hundreds of gigabytes per user. It buys you a constant factor against a problem that is not constant."],
  pick: "Always, as a floor. Every major open model ships it. But it is a <em>baseline</em>, not an answer — which is the whole reason MLA and the hybrid schedules exist.",
},
{
  id: "ntk", date: "2023-06-28", year: 2023, lane: "position",
  name: "NTK-aware scaled RoPE", who: "bloc97, r/LocalLLaMA",
  src: "reddit r/LocalLLaMA · 14lz7j5", url: "https://www.reddit.com/r/LocalLLaMA/comments/14lz7j5/",
  tag: "★ not a paper",
  starred: true,
  problem: "RoPE breaks past its training length, and the community had just been handed a 2K-context LLaMA it very much wanted to use at 8K. Position Interpolation existed but crushed high-frequency detail by scaling every dimension equally.",
  mech: "Don't scale all frequencies equally. Change the RoPE <em>base</em> so that low-frequency dimensions (long wavelengths, which genuinely run out of room) are stretched a lot, while high-frequency ones (which encode fine local order) are barely touched. Spread the interpolation pressure by wavelength.",
  buys: ["8K+ context from a 2K model with <b>no fine-tuning at all</b>, at minimal perplexity cost.", "One-line change; ran on hardware people already had, the week it was posted."],
  costs: ["A heuristic reparameterisation with no theory of where it stops.", "Degrades if pushed far, and the failure is not announced."],
  pick: "When you need more context today from a checkpoint you cannot retrain. <b>Note what this entry is:</b> the most-adopted context-extension trick of 2023 originated as a Reddit post. Peer review was not in the loop, and YaRN two months later is in part a formalisation of it.",
},
{
  id: "retnet", date: "2023-07-17", year: 2023, lane: "compute",
  name: "RetNet (retention)", who: "Sun, Dong, Huang, Ma, Xia, Xue, Wang & Wei",
  src: "arXiv:2307.08621", url: "https://arxiv.org/abs/2307.08621",
  tag: "three formulations, one model",
  problem: "Linear attention was fast and weak; transformers were strong and expensive. The 'impossible triangle' — parallel training, cheap inference, good quality — pick two.",
  mech: "Retention: a decay-weighted linear attention with three mathematically equivalent forms — <b>parallel</b> for training, <b>recurrent</b> for O(1) decoding, and <b>chunkwise recurrent</b> for long sequences.",
  buys: ["O(1) decoding cost with parallel training.", "The three-formulation framing, which is now how every linear architecture is presented."],
  costs: ["The exponential decay is fixed, which is a strong recency prior — the ALiBi problem in a different costume.", "The state still cannot correct itself; no delta rule."],
  pick: "Rarely, directly. It is on the timeline because the parallel/recurrent/chunkwise trilogy became the standard vocabulary, and because it is part of the 2023 wave where recurrence came back.",
},
{
  id: "yarn", date: "2023-08-31", year: 2023, lane: "position",
  name: "YaRN", who: "Peng, Quesnelle, Fan & Shippole",
  src: "arXiv:2309.00071", url: "https://arxiv.org/abs/2309.00071",
  tag: "the extension recipe",
  problem: "NTK-aware works but is ad hoc, and by mid-2023 there were three competing heuristics with no principled way to choose.",
  mech: "<b>NTK-by-parts</b>: classify each RoPE dimension by whether its wavelength fits inside the training context; interpolate only the ones that don't; leave high-frequency dimensions alone entirely. Then add a <em>temperature</em> correction on the attention logits, to undo the entropy drift that interpolation causes.",
  buys: ["State-of-the-art context extension using <b>10× fewer tokens and 2.5× fewer training steps</b> than previous methods.", "Works with or without fine-tuning.", "The logit-temperature correction was a real diagnosis, not a knob — interpolation demonstrably flattens attention."],
  costs: ["It is still an extension of a mechanism that was not trained at that length.", "An extended model is measurably worse <em>at</em> the extension than a natively long-trained one. You are buying reach, not competence."],
  pick: "When you are extending a RoPE model and can afford a short fine-tune. The default recipe from late 2023 until DroPE argued the whole approach was backwards.",
},
{
  id: "sinks", date: "2023-09-29", year: 2023, lane: "memory",
  name: "Attention sinks / StreamingLLM", who: "Xiao, Tian, Chen, Han & Lewis",
  src: "arXiv:2309.17453", url: "https://arxiv.org/abs/2309.17453",
  tag: "a 4-token fix",
  problem: "Run a sliding-window cache and quality holds — until the very <b>first</b> tokens fall out of the window, at which point the model collapses completely. Nobody could explain why the first tokens mattered.",
  mech: "The diagnosis is the contribution. Softmax must sum to one, so a head with nothing it wants must still put its weight <em>somewhere</em> — and it learns to dump it on the first few tokens regardless of content. Those are attention sinks. Evict them and every softmax in the model is forced to redistribute that mass into noise. So: pin 4 initial tokens permanently, and slide the window over everything else.",
  buys: ["Stable streaming to <b>4M+ tokens</b> with a fixed-size cache and <b>no fine-tuning</b>.", "Up to 22× speedup over recomputing the window.", "An explanation for a pathology the field had been routing around for years."],
  costs: ["<b>It does not extend context.</b> The model still cannot use anything in the evicted middle — it just stops catastrophically failing.", "Four tokens of cache are now permanently spoken for."],
  pick: "Long-running chat or streaming where you need bounded memory and good recent-context quality. Read it for the diagnosis even if you never ship the fix — it explains a mechanism, not just a workaround.",
},
{
  id: "ring", date: "2023-10-03", year: 2023, lane: "compute",
  name: "Ring Attention", who: "Liu, Zaharia & Abbeel",
  src: "arXiv:2310.01889", url: "https://arxiv.org/abs/2310.01889",
  tag: "buy length with hardware",
  problem: "FlashAttention made attention memory-linear on <em>one</em> device. The remaining limit is that one device's memory.",
  mech: "Shard the sequence across devices. Each device holds a block of queries and passes its K/V block around a ring, overlapping the communication with the blockwise computation so the transfer is free.",
  buys: ["Context scales with <b>device count</b> — millions of tokens, given enough hardware.", "Exact. No approximation anywhere."],
  costs: ["<b>It buys length with money.</b> Total FLOPs are unchanged; you have only parallelised them.", "Needs high-bandwidth interconnect, or the overlap stops hiding the transfer."],
  pick: "When you have the cluster and need exact long-context <em>training</em>. It is the honest baseline every approximation should be measured against.",
},
{
  id: "mamba", date: "2023-12-01", year: 2023, lane: "compute",
  name: "Mamba (selective state space)", who: "Gu & Dao",
  src: "arXiv:2312.00752", url: "https://arxiv.org/abs/2312.00752",
  tag: "recurrence, seriously",
  problem: "State-space models were fast and linear but bad at content-based reasoning, because their dynamics were <b>input-independent</b> — the same recurrence ran regardless of what the token said.",
  mech: "Make the SSM parameters functions of the input, so the model can selectively remember or forget based on content. That breaks the convolutional structure the speed depended on, so pair it with a hardware-aware parallel scan.",
  buys: ["5× higher decoding throughput than transformers, linear in T.", "A 3B model beating transformers twice its size, which is what made the field take recurrence seriously again."],
  costs: ["Still one fixed state, so exact recall of an arbitrary earlier token stays the weak point.", "That weakness is precisely why pure-Mamba models lost to hybrids."],
  pick: "Rarely alone in 2026 — but this is the entry that reopened the recurrent line after four years of transformers-only, and every hybrid below descends from the argument it won.",
},
{
  id: "mtp", date: "2024-04-30", year: 2024, lane: "core",
  name: "Multi-token prediction", who: "Gloeckle, Youbi Idrissi, Rozière, Lopez-Paz & Synnaeve (Meta)",
  src: "arXiv:2404.19737", url: "https://arxiv.org/abs/2404.19737",
  tag: "not an attention variant",
  problem: "Next-token prediction gives one gradient signal per position, and teaches the model to be locally greedy.",
  mech: "n independent output heads on a shared trunk, predicting t+1 through t+n at once.",
  buys: ["Better models on the same data, with the gain <em>growing</em> with scale.", "A free draft model for self-speculative decoding — up to 3× faster inference with no separate network."],
  costs: ["Extra heads cost training memory.", "The benefit is <b>negative at small scale</b> — it only pays above a certain size, which is an unusually honest result to publish."],
  pick: "At scale, and when you want speculative decoding for free. It is on this timeline for one reason: DeepSeek-V3 and LightningLM V4 both ship it, and it is routinely mistaken for an attention mechanism. It is not — it is a training objective.",
},
{
  id: "mla", date: "2024-05-07", year: 2024, lane: "memory",
  name: "MLA (multi-head latent attention)", who: "DeepSeek-AI (DeepSeek-V2)",
  src: "arXiv:2405.04434", url: "https://arxiv.org/abs/2405.04434",
  tag: "compress, don't share",
  problem: "MQA and GQA both cut the cache by <b>sharing</b> heads — a blunt instrument that throws away head diversity to save bytes. Is there a way to keep the diversity and lose the bytes?",
  mech: "Project K and V jointly down into a single low-rank <b>latent</b> vector and cache only that; reconstruct per-head keys and values on the fly, folding the up-projection into the query and output matrices so it costs nothing extra at inference. RoPE needs a decoupled extra dimension, because rotation does not commute with the compression.",
  buys: ["<b>93.3% KV-cache reduction</b> against the previous dense model.", "<b>Better</b> quality than MHA, not merely equal — the low-rank bottleneck acts as a regulariser.", "5.76× generation throughput."],
  costs: ["Substantially more complex than GQA.", "The RoPE interaction is genuinely fiddly and is where most reimplementations go wrong.", "The up-projection folding is an inference-time trick that constrains how you can implement the layer."],
  pick: "When you are serving long context at scale and can afford the complexity. This is the strongest single answer to the memory bill — and note the shape: it beats head-sharing by <em>compressing</em> instead, which is the same move sequence compression makes one layer up.",
},
{
  id: "delta-par", date: "2024-06-10", year: 2024, lane: "memory",
  name: "DeltaNet, parallelised", who: "Yang, Wang, Zhang, Shen & Kim",
  src: "arXiv:2406.06484", url: "https://arxiv.org/abs/2406.06484",
  tag: "★ no new idea",
  starred: true,
  problem: "The delta rule (2021) was correct and unusable, because its update is sequential and a GPU cannot work with that.",
  mech: "Reparameterise the sequence of rank-1 delta updates as a matrix product via the WY representation, turning the recurrence into <b>chunked matrix multiplications</b>. Plus a memory-efficient algorithm that avoids materialising the per-step state matrices.",
  buys: ["DeltaNet trains at scale for the first time.", "A 1.3B model beating Mamba and GLA on language modelling and recall."],
  costs: ["Still a fixed state, so still lossy at long range.", "The kernel is intricate — this is a hardware paper wearing a modelling paper's clothes."],
  pick: "<b>Read this entry for its shape, not its contents.</b> It contributes no new modelling idea whatsoever. It makes a three-year-old idea runnable, and <em>that</em> is what caused adoption. The bottleneck was never the mathematics.",
},
{
  id: "diff", date: "2024-10-07", year: 2024, lane: "core",
  name: "Differential Transformer", who: "Ye, Dong, Xia, Sun, Zhu, Huang & Wei",
  src: "arXiv:2410.05258", url: "https://arxiv.org/abs/2410.05258",
  tag: "attention is also just wrong",
  problem: "Not cost — <b>correctness</b>. Transformers over-allocate attention to irrelevant context; the noise floor drowns the signal in long inputs. This is the same forced-redistribution pathology attention sinks diagnosed, seen from the other side.",
  mech: "Compute <em>two</em> softmax attention maps and subtract one from the other, scaled by a learned scalar — a differential amplifier cancelling common-mode noise.",
  buys: ["Sparser, cleaner attention patterns that emerge rather than being imposed.", "Better long-context retrieval, less hallucination, more robust in-context learning, less sensitivity to prompt ordering."],
  costs: ["Two attention maps instead of one.", "Another learned scalar with its own schedule."],
  pick: "Retrieval-heavy long context. It is on this timeline as a corrective: not every improvement to attention is about making it cheaper. Some are about it being <em>wrong</em>.",
},
{
  id: "gated-delta", date: "2024-12-09", year: 2024, lane: "memory",
  name: "Gated DeltaNet", who: "Yang, Kautz & Hatamizadeh (NVIDIA)",
  src: "arXiv:2412.06464", url: "https://arxiv.org/abs/2412.06464",
  tag: "forget in bulk, correct in detail",
  problem: "The delta rule can correct one specific association precisely but has no way to forget <em>wholesale</em>. Mamba2's gating can forget wholesale but cannot correct precisely. Each has exactly what the other lacks.",
  mech: "Take both: <code>S ← α(S − βSkkᵀ) + βvkᵀ</code>. A decay gate α clears the state in bulk; the delta term edits one association at a time.",
  buys: ["Beats Mamba2 and DeltaNet across language modelling, recall and long-context benchmarks.", "This is the linear layer that actually shipped — Qwen3-Next and LightningLM V4 both use this family."],
  costs: ["Still a fixed state. It is a better compression, not an escape from compression.", "Still needs occasional exact-attention layers beside it, which is why <em>every</em> deployment of it is a hybrid."],
  pick: "As the recurrent layer in a hybrid schedule. In 2026 this is the default answer for 'the cheap layer' — and the fact that nobody runs it alone is the point of the next two entries.",
},
{
  id: "minimax", date: "2025-01-14", year: 2025, lane: "compute",
  name: "Lightning attention at scale", who: "MiniMax (MiniMax-01)",
  src: "arXiv:2501.08313", url: "https://arxiv.org/abs/2501.08313",
  tag: "linear, at frontier scale",
  problem: "Every linear-attention result was at small or mid scale. Nobody had shown the family survives at the frontier, where the quality bar is set.",
  mech: "Linear attention with an IO-aware tiled kernel, deployed in a <b>456B</b> MoE (45.9B active) on a 7:1 linear-to-softmax hybrid schedule, with millions of tokens of context in both training and inference.",
  buys: ["The first demonstration that linear attention holds at frontier scale.", "Context 20–32× longer than contemporaries at comparable quality."],
  costs: ["It still needs the softmax layers — the 1-in-8 is not decoration.", "The ratio was chosen, not derived."],
  pick: "Cited as evidence rather than adopted directly. Its role on the timeline is that it made <em>hybrids</em> credible above 100B, which is what the rest of 2025 builds on.",
},
{
  id: "nsa", date: "2025-02-16", year: 2025, lane: "compute",
  name: "NSA (native sparse attention)", who: "Yuan et al. (DeepSeek)",
  src: "arXiv:2502.11089", url: "https://arxiv.org/abs/2502.11089",
  tag: "sparse from pretraining",
  problem: "For <b>six years</b> sparse attention had been an inference trick bolted onto a densely-trained model. The model never learned to be sparse; you just stopped handing it keys and hoped.",
  mech: "Three branches per query, combined by a learned gate — <b>compressed</b> coarse blocks for global context, <b>selected</b> fine-grained blocks for precision, and a <b>sliding window</b> for locality. Every branch is differentiable, and block selection is aligned to the GPU's memory-access granularity so the sparsity is real rather than notional.",
  buys: ["Sparse <b>from pretraining</b>, so the model learns to use the structure instead of tolerating it.", "Matches or beats <em>full</em> attention on long-context benchmarks — not just 'close enough'.", "Large real speedups at 64K, because the kernel was co-designed with the pattern."],
  costs: ["Three branches is genuine architectural complexity.", "Block-level selection can still miss a token-level needle."],
  pick: "When training from scratch for long context. The lesson is the gap: <b>2019 → 2025</b>. The idea was never the hard part.",
},
{
  id: "qwen-next", date: "2025-09-11", year: 2025, lane: "memory",
  name: "Hybrid depth schedule (Qwen3-Next)", who: "Qwen Team",
  src: "Qwen3-Next-80B-A3B release", url: "https://huggingface.co/Qwen/Qwen3-Next-80B-A3B-Instruct",
  tag: "★ the answer is a schedule",
  starred: true,
  problem: "Linear layers are cheap and lossy; softmax layers are exact and expensive. Both statements are true, so why is this a choice you make once for the whole network?",
  mech: "48 layers as <b>12 repeats of 3 Gated DeltaNet blocks : 1 Gated Attention block</b> — 36 linear layers and 12 softmax layers. The recurrent layers carry a fixed-size state; the periodic attention layers restore exact token access.",
  buys: ["Linear cost for three-quarters of the depth, with regular exact lookups.", "80B total parameters, 3B active."],
  costs: ["The ratio is empirical. Nobody has derived it.", "You now have two layer types to tune, quantise and serve."],
  pick: "<b>This is the current shape of the answer.</b> And it is worth one comparison: LightningLM V4's DDDGDDDG motif is 6 DeltaNet to 2 GSA — <b>the same 3:1 ratio</b>, reached independently on different hardware. Two labs converging on one number is not proof of optimality, but it is a great deal more than 'we tried it and it worked'.",
},
{
  id: "dsa", date: "2025-09-29", year: 2025, lane: "compute",
  name: "DSA (DeepSeek sparse attention)", who: "DeepSeek-AI (V3.2-Exp)",
  src: "DeepSeek-V3.2-Exp release · arXiv:2512.02556", url: "https://arxiv.org/abs/2512.02556",
  tag: "the 2019 catch, answered",
  problem: "The catch nobody had solved since 2019: naïve top-k must score <em>every</em> key to discover the top k, so it saves the value work but not the scoring work. If scoring was the expensive part, you have saved nothing.",
  mech: "A <b>lightning indexer</b> — a tiny few-head scorer that runs in FP8 — cheaply ranks previous tokens; fine-grained top-k selection then sends only the winners to full attention. The indexer never produces output; it only decides what deserves the expensive read.",
  buys: ["O(Tk) instead of O(T²), at benchmark parity with the dense V3.1.", "~<b>50% lower long-context API cost</b> — the first time this literature showed up on a price list rather than a benchmark table."],
  costs: ["The indexer is another model to train, and it can mis-rank.", "k is a hyperparameter that binds, and its ceiling is often set by kernel limits rather than by quality."],
  pick: "When serving long context commercially. It closes a loop opened six years earlier by answering the objection directly: yes, you need a cheap proposal step — here is one.",
},
{
  id: "drope", date: "2025-12-13", year: 2025, lane: "position",
  name: "DroPE", who: "Gelberg, Eguchi, Akiba & Cetin (Sakana AI)",
  src: "arXiv:2512.12167", url: "https://arxiv.org/abs/2512.12167",
  tag: "★ delete the position",
  starred: true,
  problem: "Eight years and five position mechanisms, and every one of them is out of distribution past its training length. NTK-aware and YaRN rescale the rotation — but the rotation is the thing that fails.",
  mech: "Stop rescaling. <b>Remove</b> the positional encoding after pretraining, then run a short recalibration (&lt;1% of the pretraining budget) at the <em>original</em> context length, with QKNorm to stabilise the larger gradients that appear once the positional bias is gone. The claim underneath: positional encoding is an inductive bias that <em>helps convergence</em> and then <em>blocks generalisation</em>, so its job ends before training does.",
  buys: ["Zero-shot context extension with <b>no long-context fine-tuning</b>.", "Outperforms rotary-scaling methods on LongBench and RULER.", "Retains needle-in-a-haystack performance at 2×/4×/8× where scaling methods collapse; evaluated on extraction beyond 80×."],
  costs: ["You must own the pretraining run — this is not an inference-time switch.", "Validated on standard RoPE transformers up to 7B; anything else is a replication, not a reproduction.", "Dropping the encoding <em>early</em> degrades the model; the ordering matters and is not optional."],
  pick: "When you control training and long context is the actual goal. <b>One caveat worth stating plainly:</b> LightningLM V4 replicated the procedure inside a DeltaNet/sparse hybrid and reports a clean ~0.12-nat recovery — but its own cookbook says the resulting long-context reach there is “reported here as theoretical for this model rather than measured”, and that “the longer reaches were not tested in this work.” The procedure transferred. The 256K number was never measured.",
},
];
